
export const moviesConstants = [
    {
        image: 'https://bipbap.ru/wp-content/uploads/2017/04/0_7c779_5df17311_orig.jpg',
        title: '33 слова о дизайне',
        save: 'true',
        duration: '1ч 47м',
        _id: 1,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSReqqfYBY9dXOJhkr2JD4ok14KiDMersrpTGrATeQeEQtiJuJVa3f9fgZiw0gk5mw0Q44&usqp=CAU',
        title: 'Киноальманах «100 лет дизайна»',
        save: 'false',
        duration: '1ч 3м',
        _id: 2,
    },
    {
        image: 'https://klike.net/uploads/posts/2019-11/1572607663_1.jpg',
        title: 'В погоне за Бенкси',
        save: 'false',
        duration: '1ч 42м',
        _id: 3,
    },
    {
        image: 'https://vjoy.cc/wp-content/uploads/2020/08/680x453_1_e58a11477abe2c1cac712741097d5a4a@690x460_0xc0a8392b_311082981484569859.jpeg',
        title: 'Баския: Взрыв реальности',
        save: 'false',
        duration: '1ч 21м',
        _id: 4,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaVInulyITqOv0xSrxvUEJkmYaPs_T2eYwfdfZCDz8AuUrWvt9B3Y6P9Fg3r_iINLracA&usqp=CAU',
        title: 'Бег это свобода',
        save: 'false',
        duration: '1ч 44м',
        _id: 5,
    },
    {
        image: 'https://media.istockphoto.com/id/618651752/es/foto/bora-bora-tahiti-flores.jpg?s=612x612&w=0&k=20&c=k64W_-VgAb0rFHd4iAUP_qRaK27nEsm-Zz_qgn6h5v8=',
        title: 'Книготорговцы',
        save: 'true',
        duration: '1ч 37м',
        _id: 6,
    },
    {
        image: 'https://sutochno.ru/doc/images/galleries/182/more3.jpg',
        title: 'Когда я думаю о Германии ночью',
        save: 'false',
        duration: '1ч 56м',
        _id: 7,
    },
    {
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT7jAndNCGbBp2UWTu9J9YJnHP9p03IbbS0w&usqp=CAU',
        title: 'Gimme Danger. История Игги и The Stooges',
        save: 'false',
        duration: '1ч 17м',
        _id: 8,
    },
    {
        image: 'https://kipmu.ru/wp-content/uploads/pchmnmr-scaled.jpg',
        title: 'Дженис: Маленькая девочка грустит',
        save: 'true',
        duration: '1ч 42м',
        _id: 9,
    },
    {
        image: 'https://cs11.pikabu.ru/post_img/2019/07/07/12/1562530276168517093.jpg',
        title: 'Соберись перед прыжком',
        save: 'true',
        duration: '1ч 10м',
        _id: 10,
    },
    {
        image: 'https://regnum.ru/uploads/pictures/news/2018/11/27/regnum_picture_15433128755970594_normal.png',
        title: 'Пи Джей Харви: A dog called money',
        save: 'false',
        duration: '1ч 4м',
        _id: 11,
    },
    {
        image: 'https://uznayvse.ru/images/stories/uzn_1358920097.jpg',
        title: 'По волнам: Искусство звука в кино',
        save: 'false',
        duration: '1ч 7м',
        _id: 13,
    },
]

export const moviesSaveConstants = [
    {
        image: 'https://bipbap.ru/wp-content/uploads/2017/04/0_7c779_5df17311_orig.jpg',
        title: '33 слова о дизайне',
        save: 'true',
        duration: '1ч 47м',
        _id: 1,
    },
    {
        image: 'https://kipmu.ru/wp-content/uploads/pchmnmr-scaled.jpg',
        title: 'Дженис: Маленькая девочка грустит',
        save: 'true',
        duration: '1ч 42м',
        _id: 2,
    },
    {
        image: 'https://cs11.pikabu.ru/post_img/2019/07/07/12/1562530276168517093.jpg',
        title: 'Соберись перед прыжком',
        save: 'true',
        duration: '1ч 10м',
        _id: 3,
    },
]